### ISSUE TITLE
Add tests and fix encoding err on signedCommitment

### ISSUE THREAD

**Issue by thomasmodeneis** [ComposableFi/relayer#7]
file: `relayer/provider/substrate/construct.go`

```
panic: signedCommitment, err is here, try 2

goroutine 29 [running]:
github.com/cosmos/relayer/v2/relayer/provider/substrate.signedCommitment(0x0, {0x4a, 0xd2, 0x62, 0x2f, 0x54, 0xd4, 0x98, 0xa3, 0xd4, ...})
        /opt/gocode/src/github.com/ComposableFi/relayer/relayer/provider/substrate/construct.go:165 +0x1c6
github.com/cosmos/relayer/v2/relayer/provider/substrate.(*SubstrateProvider).QueryHeaderAtHeight(0xc001156930, {0x0, 0x0}, 0x1a22)
        /opt/gocode/src/github.com/ComposableFi/relayer/relayer/provider/substrate/query.go:49 +0xed
github.com/cosmos/relayer/v2/relayer/provider/substrate.(*SubstrateProvider).GetIBCUpdateHeader(...)
        /opt/gocode/src/github.com/ComposableFi/relayer/relayer/provider/substrate/tx.go:780
github.com/cosmos/relayer/v2/relayer/provider/substrate.(*SubstrateProvider).GetLightSignedHeaderAtHeight(0x0, {0x1a9c078, 0xc0010e6180}, 0x0)
        /opt/gocode/src/github.com/ComposableFi/relayer/relayer/provider/substrate/tx.go:771 +0x25
github.com/cosmos/relayer/v2/relayer.GetLightSignedHeadersAtHeights.func2()
        /opt/gocode/src/github.com/ComposableFi/relayer/relayer/query.go:143 +0x3e
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /opt/gocode/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /opt/gocode/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92

```

**Comment by Kaktus-green** [comment]
Hey, just wanted to check what is the current status of this issue? Dragan here :)
